# Generated by Django 4.1.4 on 2022-12-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('doctor', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('room', models.IntegerField()),
            ],
        ),
    ]
